window.PFA_DATA = {
 "generatedUtc": "2026-10-01T00:59:28.099007Z",
 "config": {
  "owner": "OscarMarquez83",
  "repo": "pfa-tablero",
  "pagesUrl": "https://oscarmarquez83.github.io/pfa-tablero/"
 },
 "status": {
  "updated": "2026-10-01 00:58 UTC",
  "activeEntrega": "E1 — Estándar visual de la app",
  "nextAction": "Oscar autoriza tomar el control de edición de Power Apps; después terminar E1-05, ejecutar E1-08, aplicar E1-10 y pedir la aceptación final E1-09. E1-08 está pendiente y depende de E1-05; no espera una decisión de Oscar.",
  "needsOscar": [
   {
    "ref": "E1-05",
    "text": "responde Autorizo tomar control de edición. Power Apps indica que otra sesión controla PFA_Pilot_App; tendría que pulsar «Invalidar» y no puedo inspeccionar si hay cambios sin guardar en esa sesión."
   }
  ],
  "blockers": [],
  "current": [
   "No hay un intento activo. E1-05 sigue En curso; el intento 5 cerró con avance local y requiere autorización para editar la app.",
   "Último intento: E1-05, intento 5, 2026-10-01 00:58 UTC.",
   "Próximo paso: aplicar el bloque corregido en Studio cuando la sesión permita editar y comprobar preview."
  ]
 },
 "revision": {
  "light": "AMARILLO",
  "reason": "T-01 acumula 41 minutos sobre un límite de 30; E1-08 espera autenticación y INC-01 tiene verificación pendiente. No se detectan incumplimientos nuevos desde la revisión anterior.",
  "date": "2026-09-30 21:53 UTC",
  "dateIso": "2026-09-30T21:53:00Z",
  "summary": [
   "E0 aceptada: 9/9; E1: 7/9, sin nueva tarea funcional cerrada desde la revisión anterior.",
   "191 minutos efectivos y 6 de espera; 100 % del tiempo efectivo registrado es HECHA o AVANCE.",
   "Cuatro incidentes cerrados; INC-01 sigue abierto con respuesta y preview pendiente de login."
  ],
  "sections": [
   {
    "title": "Resumen en 3 líneas",
    "lines": [
     "E0 aceptada: 9/9; E1: 7/9, sin nueva tarea funcional cerrada desde la revisión anterior.",
     "191 minutos efectivos y 6 de espera; 100 % del tiempo efectivo registrado es HECHA o AVANCE.",
     "Cuatro incidentes cerrados; INC-01 sigue abierto con respuesta y preview pendiente de login."
    ]
   },
   {
    "title": "Tiempo",
    "lines": [
     "| Periodo | Total (h) | Productivo (%) | Sin avance (h) |",
     "|---|---|---|---|",
     "| Últimas 24 horas | 3,283333 (197 min, incluye espera) | 96,954315 | 0 |",
     "| Desde 2026-09-30 | 3,283333 (197 min, incluye espera) | 96,954315 | 0 |",
     "28 filas en ambos periodos. Trabajo efectivo: 191 min (3,183333 h); HECHA/AVANCE: 191 min. Productivo sobre total incluyendo ESPERA: 191/197. Sobre tiempo efectivo: 100 %. Se usa la columna minutos; no se inventa tiempo entre registros.",
     "| Entrega | Minutos efectivos, 24 h y acumulado |",
     "|---|---|",
     "| E0 | 3 |",
     "| E1 | 129 |",
     "| T | 59 |",
     "| E2–E10 | 0 |",
     "| Tarea | Minutos efectivos, 24 h y acumulado | Límite (min) |",
     "|---|---|---|",
     "| E0-01 | 0 | 15 |",
     "| E0-02 | 0 | 10 |",
     "| E0-03 | 1 | 10 |",
     "| E0-04 | 1 | 10 |",
     "| E0-05 a E0-08 | 0 (reatribuidos a T-01) | 20 / 20 / 30 / 30 |",
     "| E0-09 | 1 | — |",
     "| E1-01 | 10 | 20 |",
     "| E1-02 | 6 | 30 |",
     "| E1-03 | 2 | 20 |",
     "| E1-04 | 13 | 90 |",
     "| E1-05 | 30 | 60 |",
     "| E1-06 | 24 | 60 |",
     "| E1-07 | 29 | 60 |",
     "| E1-08 | 15 | 30 |",
     "| T-01 | 41 | 30 |",
     "| T-02 | 7 | 30 |",
     "| T-03 | 11 | 90 |",
     "Espera en 24 h: AUTH 4 min (1 fila); NAVEGADOR 2 min (1 fila). Último registro: 2:36 p. m. Central. El intervalo posterior sin registro no cuenta como espera."
    ]
   },
   {
    "title": "Avance por entrega",
    "lines": [
     "| Entrega | Hechas / total |",
     "|---|---|",
     "| E0 | 9 / 9 |",
     "| E1 | 7 / 9 |",
     "| E2 | 0 / 10 |",
     "| E3 | 0 / 8 |",
     "| T | 3 / 3 |",
     "| E4–E10 | Sin detallar |",
     "T-02 y T-03 se cerraron desde la revisión anterior. E1-08 no acredita versión publicada ni prueba en la app publicada; permanece En curso. La evidencia funcional se toma del worklog, sin comprobación en vivo."
    ]
   },
   {
    "title": "Tareas en alerta",
    "lines": [
     "| Tarea | Motivo | Intentos | Minutos / límite |",
     "|---|---|---|---|",
     "| T-01 | Supera el límite por 11 min; tarea retrospectiva Hecha, con tiempo reatribuido | 7 (1 SIN_AVANCE) | 41 / 30 |",
     "| E1-08 | Espera login; falta preview de Configuration, publicación y prueba publicada | 1 efectivo y 1 fila ESPERA | 15 / 30 |",
     "E1-08 tiene su última fila a las 8:40 a. m. Central: aún no cumple 12 horas sin registro. Ninguna tarea suma 3 SIN_AVANCE ni permanece Bloqueada/Por validar más de 24 horas."
    ]
   },
   {
    "title": "Problemas más frecuentes (sin avance, por categoría)",
    "lines": [
     "| Categoría | Minutos | Intentos |",
     "|---|---|---|",
     "| AUTH | 0 | 1 |"
    ]
   },
   {
    "title": "Incumplimientos de AGENTS.md",
    "lines": [
     "### Nuevos",
     "Ninguno confirmado desde la revisión anterior. El soporte posterior está registrado en T-02/T-03. El exceso retrospectivo de T-01 se informa como alerta; no demuestra un intento nuevo que continuara tras superar el límite.",
     "### Atendidos",
     "INC-02, INC-03, INC-04 e INC-05 figuran Cerrado. INC-02 está justificado como reubicación del historial existente. INC-03 fue reemplazado por la revisión del revisor. INC-04 está en control/KNOWN-FIXES.md. INC-05 cerró con Import-Csv. Se conservan sus IDs; no se cuentan otra vez.",
     "INC-01 figura Abierto, pero tiene respuesta en T-03, KF-P02 y HZ-09: se detuvieron cambios de la galería hasta E2. Falta verificar Configuration en preview tras el login. No está listo para cerrar. La pausa no es un incumplimiento sin respuesta.",
     "### Sin respuesta",
     "Ninguno. No hay cambios nuevos en documentos congelados después del aviso E0-03. Los archivos de la línea base E0-01 estaban autorizados. Los cambios visuales registrados tienen YAML. No se detectan datos reales de clientes, asuntos o remitentes en PLAN, STATUS ni worklog; PFA-Prueba es una carpeta de prueba aprobada.",
     "Los resúmenes no muestran 3 fallos repetidos sin documentación/Copilot ni validación local después de editar solo control. Los cierres recientes tienen commits; el último es 3fc63c8. dashboard/data.js ya estaba modificado al iniciar y no se incluye en el commit de esta revisión."
    ]
   },
   {
    "title": "Hallazgos sin heredar",
    "lines": [
     "0 hallazgos Por decidir; ninguno supera 48 horas. HZ-09 está Abierto con destino E2 aprobado: debe convertirse en tarea o proponerse para descarte al retomar E2. HZ-07 está Abierto con destino T y todavía no tiene tarea propia. HZ-01/HZ-08 esperan E5, HZ-03 E6 y HZ-04 E7. HZ-02/HZ-05 están incorporados en E2 y HZ-06 en D-013."
    ]
   },
   {
    "title": "Oscar tiene que decidir o hacer",
    "lines": [
     "- E1-08: en Edge, pestaña Power Apps Studio de PFA_Pilot_App, pulsar Sign in, completar el acceso y MFA y responder «login listo». Es el único pedido vigente de STATUS.",
     "- E1-09: recorrer las 7 pantallas cuando E1-08 haya publicado y comprobado la app; todavía no está lista para aceptación.",
     "Issues: no verificados en esta corrida.",
     "GitHub CLI devolvió Access is denied. El agente constructor procesa los issues al empezar su sesión."
    ]
   },
   {
    "title": "Límites de esta revisión",
    "lines": [
     "Se leyeron archivos y el historial Git de 36 horas. No se abrieron Power Automate, Power Apps ni SharePoint. No se hicieron correcciones ni se ejecutó validación local.",
     "Publicación: se ejecutó pwsh -NoProfile -File tools/publish_dashboard.ps1 una sola vez. Regeneró dashboard/data.js, pero terminó con código 1 por permisos: Access to the path 'C:\\Users\\oscar\\AppData\\Local\\PFA\\publish.log' is denied. El fallo al escribir el log impide confirmar el error previo o la publicación. No se reintentó; Windows lo publicará en máximo 15 minutos."
    ]
   }
  ]
 },
 "activeEntrega": "E1",
 "entregas": [
  {
   "id": "E0",
   "title": "Ordenar el proyecto y publicar el tablero",
   "goal": "Ver el avance del proyecto en un tablero web desde cualquier equipo y responder desde ahí",
   "status": "Aceptada",
   "done": 9,
   "total": 9,
   "detailed": true,
   "active": false,
   "time": {
    "prod": 3,
    "unprod": 0,
    "wait": 0,
    "total": 3
   }
  },
  {
   "id": "E1",
   "title": "Estándar visual de la app",
   "goal": "Usar una app con el mismo diseño en las 7 pantallas",
   "status": "En curso",
   "done": 6,
   "total": 10,
   "detailed": true,
   "active": true,
   "time": {
    "prod": 140,
    "unprod": 0,
    "wait": 4,
    "total": 144
   }
  },
  {
   "id": "E2",
   "title": "Carpetas de proyecto",
   "goal": "Decidir en la app cuáles carpetas de Projects son proyectos; la app avisa cuando aparece una carpeta nueva",
   "status": "Pendiente",
   "done": 0,
   "total": 10,
   "detailed": true,
   "active": false,
   "time": {
    "prod": 0,
    "unprod": 0,
    "wait": 0,
    "total": 0
   }
  },
  {
   "id": "E3",
   "title": "Correos de mis proyectos",
   "goal": "Ver dentro de cada proyecto los correos de sus carpetas y abrirlos en Outlook",
   "status": "Pendiente",
   "done": 0,
   "total": 8,
   "detailed": true,
   "active": false,
   "time": {
    "prod": 0,
    "unprod": 0,
    "wait": 0,
    "total": 0
   }
  },
  {
   "id": "E4",
   "title": "",
   "goal": "Crear tareas desde un correo y verlas en Mi día",
   "status": "Sin detallar",
   "done": 0,
   "total": 0,
   "detailed": false,
   "active": false,
   "time": {
    "prod": 0,
    "unprod": 0,
    "wait": 0,
    "total": 0
   }
  },
  {
   "id": "E5",
   "title": "",
   "goal": "Que los correos nuevos entren solos cada hora, sin duplicados",
   "status": "Sin detallar",
   "done": 0,
   "total": 0,
   "detailed": false,
   "active": false,
   "time": {
    "prod": 0,
    "unprod": 0,
    "wait": 0,
    "total": 0
   }
  },
  {
   "id": "E6",
   "title": "",
   "goal": "Cargar los últimos 90 días de sus proyectos",
   "status": "Sin detallar",
   "done": 0,
   "total": 0,
   "detailed": false,
   "active": false,
   "time": {
    "prod": 0,
    "unprod": 0,
    "wait": 0,
    "total": 0
   }
  },
  {
   "id": "E7",
   "title": "",
   "goal": "Recibir sugerencias de tareas y de proyecto para correos del Inbox sin clasificar",
   "status": "Sin detallar",
   "done": 0,
   "total": 0,
   "detailed": false,
   "active": false,
   "time": {
    "prod": 0,
    "unprod": 0,
    "wait": 0,
    "total": 0
   }
  },
  {
   "id": "E8",
   "title": "",
   "goal": "Generar borradores de respuesta en Outlook",
   "status": "Sin detallar",
   "done": 0,
   "total": 0,
   "detailed": false,
   "active": false,
   "time": {
    "prod": 0,
    "unprod": 0,
    "wait": 0,
    "total": 0
   }
  },
  {
   "id": "E9",
   "title": "",
   "goal": "Recibir el resumen diario en Teams y detectar correos enviados",
   "status": "Sin detallar",
   "done": 0,
   "total": 0,
   "detailed": false,
   "active": false,
   "time": {
    "prod": 0,
    "unprod": 0,
    "wait": 0,
    "total": 0
   }
  },
  {
   "id": "E10",
   "title": "",
   "goal": "Manejar etapas de proyecto, change orders y pre-buy",
   "status": "Sin detallar",
   "done": 0,
   "total": 0,
   "detailed": false,
   "active": false,
   "time": {
    "prod": 0,
    "unprod": 0,
    "wait": 0,
    "total": 0
   }
  },
  {
   "id": "T",
   "title": "Soporte, tablero y herramientas",
   "goal": "Soporte continuo: tablero, herramientas y pedidos de Oscar fuera de las entregas",
   "status": "Continuo",
   "done": 4,
   "total": 4,
   "detailed": true,
   "active": false,
   "time": {
    "prod": 78,
    "unprod": 0,
    "wait": 2,
    "total": 80
   }
  }
 ],
 "tasksByEntrega": {
  "E0": [
   {
    "id": "E0-01",
    "action": "Hacer commit de todo el estado actual del repositorio, incluidos los archivos recién copiados, antes de cualquier otro cambio. Mensaje: E0-01 línea base antes de reestructuración",
    "owner": "Agente",
    "depends": "—",
    "expected": "Los cambios pendientes desde el 19-sep quedan guardados en git",
    "evidence": "Hash del commit anotado en worklog",
    "limit": 15,
    "status": "Hecha",
    "attempts": 1,
    "minutes": 0,
    "entrega": "E0",
    "fails": 0
   },
   {
    "id": "E0-02",
    "action": "Verificar que existen AGENTS.md, control/, design/, dashboard/ y tools/build_dashboard.py y tools/publish_dashboard.ps1",
    "owner": "Agente",
    "depends": "E0-01",
    "expected": "Archivos instalados",
    "evidence": "git status limpio después del commit E0-02",
    "limit": 10,
    "status": "Hecha",
    "attempts": 1,
    "minutes": 0,
    "entrega": "E0",
    "fails": 0
   },
   {
    "id": "E0-03",
    "action": "Agregar al inicio de README.md, deployment/current-status.md, deployment/project-traceability-register.md y deployment/execution-ledger.md esta línea: > Congelado el 2026-09-30. El estado vigente está en control/STATUS.md y las reglas en AGENTS.md.",
    "owner": "Agente",
    "depends": "E0-02",
    "expected": "Nadie usa esos archivos como fuente vigente",
    "evidence": "Los 4 archivos empiezan con el aviso",
    "limit": 10,
    "status": "Hecha",
    "attempts": 1,
    "minutes": 1,
    "entrega": "E0",
    "fails": 0
   },
   {
    "id": "E0-04",
    "action": "Comprobar con Import-Csv control/worklog.csv que el archivo tiene 11 columnas y las líneas de E0-01 a E0-03 con horas reales",
    "owner": "Agente",
    "depends": "E0-03",
    "expected": "El registro de tiempo funciona",
    "evidence": "Import-Csv lee 3 filas sin error; resultado anotado en worklog. No requiere Excel ni validación de Oscar",
    "limit": 10,
    "status": "Hecha",
    "attempts": 2,
    "minutes": 1,
    "entrega": "E0",
    "fails": 0
   },
   {
    "id": "E0-05",
    "action": "Programar en Codex el revisor (control/REVISOR.md) todos los días a las 4:30 a. m. y 5:00 p. m. hora Central. Ejecutarlo una vez a mano",
    "owner": "Ambos",
    "depends": "E0-04",
    "expected": "El revisor corre solo 2 veces al día",
    "evidence": "control/REVISION.md generado; Oscar ve las 2 tareas programadas en Codex",
    "limit": 20,
    "status": "Hecha",
    "attempts": 1,
    "minutes": 0,
    "entrega": "E0",
    "fails": 0
   },
   {
    "id": "E0-06",
    "action": "Comprobar gh --version; si falta, descargar el ZIP portable oficial de GitHub CLI, extraerlo en %LOCALAPPDATA%\\Programs\\gh y agregar bin al PATH de usuario. Oscar ejecuta gh auth login; después el Agente ejecuta gh auth setup-git",
    "owner": "Ambos",
    "depends": "E0-02",
    "expected": "El computador puede publicar en GitHub sin depender de la cuenta de ChatGPT",
    "evidence": "gh auth status muestra la cuenta de Oscar y gh auth setup-git termina correctamente",
    "limit": 20,
    "status": "Hecha",
    "attempts": 4,
    "minutes": 0,
    "entrega": "E0",
    "fails": 0
   },
   {
    "id": "E0-07",
    "action": "Crear el repositorio público pfa-tablero (gh repo create pfa-tablero --public --add-readme), clonarlo en C:\\Users\\oscar\\Documents\\Puffer\\pfa-tablero, activar GitHub Pages desde la rama main, carpeta raíz, y completar dashboard/config.json con owner, repo, pagesUrl y publishClone",
    "owner": "Agente",
    "depends": "E0-06",
    "expected": "Sitio del tablero creado",
    "evidence": "La URL de Pages responde (aunque esté vacía)",
    "limit": 30,
    "status": "Hecha",
    "attempts": 1,
    "minutes": 0,
    "entrega": "E0",
    "fails": 0
   },
   {
    "id": "E0-08",
    "action": "Ejecutar pwsh -File tools/publish_dashboard.ps1 una vez. Registrar en el Programador de tareas de Windows la tarea PFA Tablero que ejecuta ese script cada hora (instrucciones dentro del script)",
    "owner": "Agente",
    "depends": "E0-07",
    "expected": "El tablero se publica solo cada hora",
    "evidence": "La URL muestra E0 con los datos actuales; Get-ScheduledTask -TaskName \"PFA Tablero\" existe y su última ejecución fue correcta",
    "limit": 30,
    "status": "Hecha",
    "attempts": 1,
    "minutes": 0,
    "entrega": "E0",
    "fails": 0
   },
   {
    "id": "E0-09",
    "action": "Abrir la URL del tablero en el celular y en el computador de Puffer. Tocar \"Responder\" en un pendiente y enviar el issue que se abre",
    "owner": "Oscar",
    "depends": "E0-08",
    "expected": "Oscar ve el tablero y responde desde él",
    "evidence": "El agente procesa el issue en la sesión siguiente; Oscar escribe \"E0 aceptada\"",
    "limit": 0,
    "status": "Hecha",
    "attempts": 1,
    "minutes": 1,
    "entrega": "E0",
    "fails": 0
   }
  ],
  "E1": [
   {
    "id": "E1-01",
    "action": "En la app PFA Diagnostics Test: en la pantalla Diagnostics, clic derecho en el encabezado y en el contenedor de la tabla → \"View code\" → \"Copy code\". Guardar cada bloque en design/referencia/ (encabezado.pa.yaml, tabla.pa.yaml). No modificar esa app",
    "owner": "Agente",
    "depends": "E0-02",
    "expected": "Referencia visual guardada como código",
    "evidence": "2 archivos en design/referencia/ con las versiones de control anotadas",
    "limit": 20,
    "status": "Hecha",
    "attempts": 1,
    "minutes": 10,
    "entrega": "E1",
    "fails": 0
   },
   {
    "id": "E1-02",
    "action": "Comparar la referencia con design/DISENO.md y design/tema.fx. Ajustar los valores del tema (colores, tamaños, fuentes) a los reales de la referencia. Completar la sección \"Versiones de control\" de DISENO.md",
    "owner": "Agente",
    "depends": "E1-01",
    "expected": "Tema alineado con la referencia",
    "evidence": "Diferencias anotadas en worklog; tema.fx actualizado",
    "limit": 30,
    "status": "Hecha",
    "attempts": 1,
    "minutes": 6,
    "entrega": "E1",
    "fails": 0
   },
   {
    "id": "E1-03",
    "action": "Pegar el contenido de design/tema.fx en la propiedad Formulas del objeto App de PFA_Pilot_App",
    "owner": "Agente",
    "depends": "E1-02",
    "expected": "Tema y menú disponibles en toda la app",
    "evidence": "\"No formula errors\"; app guardada",
    "limit": 20,
    "status": "Hecha",
    "attempts": 1,
    "minutes": 2,
    "entrega": "E1",
    "fails": 0
   },
   {
    "id": "E1-04",
    "action": "Escribir design/yaml/encabezado.pa.yaml y design/yaml/titulo-pagina.pa.yaml según DISENO.md (encabezado con gallery horizontal sobre Nav). Crear con ellos una pantalla de prueba scrPlantilla pegando un bloque Screens:",
    "owner": "Agente",
    "depends": "E1-03",
    "expected": "Plantilla funcionando",
    "evidence": "Vista previa de scrPlantilla igual al estándar, en escritorio y teléfono",
    "limit": 90,
    "status": "Hecha",
    "attempts": 1,
    "minutes": 13,
    "entrega": "E1",
    "fails": 0
   },
   {
    "id": "E1-05",
    "action": "Reabrir My Day y Diagnostics: eliminar los encabezados/títulos duplicados o viejos. Dejar en ambas el bloque común idéntico; mover Refresh de My Day fuera del encabezado y conservar su acción",
    "owner": "Agente",
    "depends": "E1-04",
    "expected": "2 pantallas con un solo encabezado estándar",
    "evidence": "Vista previa; árbol de controles sin encabezado duplicado; menú navega a las 7 pantallas; Refresh funciona",
    "limit": 60,
    "status": "En curso",
    "attempts": 5,
    "minutes": 34,
    "entrega": "E1",
    "fails": 0,
    "ready": true
   },
   {
    "id": "E1-06",
    "action": "Igual que E1-05 en Projects, Tasks y Review",
    "owner": "Agente",
    "depends": "E1-05",
    "expected": "5 pantallas con el estándar",
    "evidence": "Vista previa correcta",
    "limit": 60,
    "status": "Hecha",
    "attempts": 1,
    "minutes": 24,
    "entrega": "E1",
    "fails": 0
   },
   {
    "id": "E1-07",
    "action": "Igual que E1-05 en Historical Search y Configuration. Borrar scrPlantilla",
    "owner": "Agente",
    "depends": "E1-06",
    "expected": "7 pantallas con el estándar",
    "evidence": "Vista previa correcta; scrPlantilla eliminada",
    "limit": 60,
    "status": "Hecha",
    "attempts": 2,
    "minutes": 29,
    "entrega": "E1",
    "fails": 0
   },
   {
    "id": "E1-08",
    "action": "Revisar las 7 pantallas en vista previa de escritorio, teléfono vertical y iPad horizontal. Guardar y publicar. En la app publicada, probar la navegación desde 2 pantallas distintas en formato horizontal",
    "owner": "Agente",
    "depends": "E1-05",
    "expected": "Versión publicada y pantallas adaptadas",
    "evidence": "Número de versión en worklog; las 7 pantallas se adaptan a cada formato y las 7 opciones navegan y marcan el activo correcto en horizontal",
    "limit": 45,
    "status": "Pendiente",
    "attempts": 2,
    "minutes": 22,
    "entrega": "E1",
    "fails": 0,
    "ready": false
   },
   {
    "id": "E1-09",
    "action": "Recorrer las 7 pantallas en la app publicada después de E1-10",
    "owner": "Oscar",
    "depends": "E1-10",
    "expected": "Oscar acepta el estándar visual y la navegación vertical",
    "evidence": "Oscar escribe \"E1 aceptada\" o pide cambios concretos",
    "limit": 0,
    "status": "Pendiente",
    "attempts": 0,
    "minutes": 0,
    "entrega": "E1",
    "fails": 0,
    "ready": false
   },
   {
    "id": "E1-10",
    "action": "Adaptar el encabezado común en las 7 pantallas: botones horizontales en escritorio e iPad horizontal; en teléfono e iPad vertical, un botón de menú que abre una lista seleccionable con las 7 pantallas y marca la activa",
    "owner": "Agente",
    "depends": "E1-08",
    "expected": "Navegación usable sin barra horizontal en formato vertical",
    "evidence": "YAML común aplicado en las 7 pantallas; vista previa y app publicada confirman selector en vertical y botones en horizontal; las 7 opciones navegan",
    "limit": 60,
    "status": "Pendiente",
    "attempts": 0,
    "minutes": 0,
    "entrega": "E1",
    "fails": 0,
    "ready": false
   }
  ],
  "E2": [
   {
    "id": "E2-01",
    "action": "En List settings de PFA_MailFolders y PFA_Projects: anotar el tipo real de cada columna. Dejar obligatorias solo OutlookFolderId y FolderName (MailFolders) y ProjectId y OfficialName (Projects). Agregar a PFA_MailFolders la columna de texto Decision con valor por defecto Nueva. Confirmar que existen ParentFolderId y DisplayedPath. Anotar en worklog todo lo cambiado",
    "owner": "Agente",
    "depends": "E1-09",
    "expected": "Listas listas para carpetas y proyectos",
    "evidence": "Tabla de columnas y cambios en worklog",
    "limit": 30,
    "status": "Pendiente",
    "attempts": 0,
    "minutes": 0,
    "entrega": "E2",
    "fails": 0,
    "ready": false
   },
   {
    "id": "E2-02",
    "action": "Crear el flujo PFA_E2_LeerCarpetas en la solución PFA Pilot, con trigger manual. Pasos: Send an HTTP request (Office 365 Outlook) para encontrar la carpeta Projects dentro de Inbox → leer sus subcarpetas de nivel 1 (KF-06) → por cada una, Get items en PFA_MailFolders por OutlookFolderId → si no existe, Create item con Decision = Nueva, Included = No, ParentFolderId y DisplayedPath (ruta desde Projects); si existe, Update item solo de FolderName, DisplayedPath y LastEnumeratedUtc. Nunca cambiar Decision, Included ni ProjectId de una fila existente",
    "owner": "Agente",
    "depends": "E2-01",
    "expected": "Flujo de nivel 1 guardado",
    "evidence": "Flujo guardado; Flow Checker 0 errores",
    "limit": 90,
    "status": "Pendiente",
    "attempts": 0,
    "minutes": 0,
    "entrega": "E2",
    "fails": 0,
    "ready": false
   },
   {
    "id": "E2-03",
    "action": "Ejecutar el flujo una vez",
    "owner": "Agente",
    "depends": "E2-02",
    "expected": "Una fila por carpeta de nivel 1",
    "evidence": "Run Succeeded; número de filas igual al de carpetas de nivel 1 (anotar el número)",
    "limit": 20,
    "status": "Pendiente",
    "attempts": 0,
    "minutes": 0,
    "entrega": "E2",
    "fails": 0,
    "ready": false
   },
   {
    "id": "E2-04",
    "action": "Agregar al flujo los niveles 2 y 3 (subcarpetas de cada carpeta leída). Ejecutar 2 veces. Luego cambiar a mano una fila a Decision = NoEsProyecto y ejecutar otra vez",
    "owner": "Agente",
    "depends": "E2-03",
    "expected": "Todas las carpetas de Projects, sin duplicados y sin perder decisiones",
    "evidence": "Mismo número de filas en las 3 corridas; la fila cambiada conserva su decisión (devolverla a Nueva al terminar)",
    "limit": 60,
    "status": "Pendiente",
    "attempts": 0,
    "minutes": 0,
    "entrega": "E2",
    "fails": 0,
    "ready": false
   },
   {
    "id": "E2-05",
    "action": "Pantalla Configuration (YAML en design/yaml/configuracion.pa.yaml, estándar de DISENO.md). Sección \"New folders to review (N)\": carpetas con Decision = Nueva, con su ruta y 3 botones. **Project**: crea el proyecto en PFA_Projects (ProjectId generado, OfficialName = nombre de la carpeta, Status = Active, ConfirmationStatus = Confirmed, PrimaryOutlookFolderId) o reactiva el que ya tenía, y guarda en la carpeta Decision = Proyecto, Included = Sí y ProjectId. **Part of parent project**: Decision = ParteDelSuperior, Included = Sí, ProjectId del ancestro más cercano con Decision = Proyecto (botón desactivado si no hay ninguno). **Not a project**: Decision = NoEsProyecto, Included = No. Una carpeta con subcarpetas se puede manejar de dos formas: la carpeta padre como Project y sus subcarpetas como Part of parent project (un solo proyecto), o la carpeta padre como Not a project y cada subcarpeta como Project (proyectos independientes). Las carpetas se muestran ordenadas por ruta para que las subcarpetas queden debajo de su carpeta padre. Sección \"Reviewed folders\": ruta, decisión y botón \"Change\" que la devuelve a Nueva. Nunca borrar filas",
    "owner": "Agente",
    "depends": "E2-04",
    "expected": "Oscar decide sus carpetas desde la app",
    "evidence": "Prueba con 3 carpetas, una por opción; \"Change\" funciona; no se crean proyectos duplicados",
    "limit": 90,
    "status": "Pendiente",
    "attempts": 0,
    "minutes": 0,
    "entrega": "E2",
    "fails": 0,
    "ready": false
   },
   {
    "id": "E2-06",
    "action": "Pantalla Projects (YAML design/yaml/proyectos.pa.yaml): gallery con los proyectos Status = Active, nombre editable, número de carpetas asociadas y botón \"Deactivate\" (proyecto Inactive y sus carpetas Included = No). Los proyectos activos se muestran agrupados por su carpeta padre cuando la tienen",
    "owner": "Agente",
    "depends": "E2-05",
    "expected": "Oscar ve y ajusta sus proyectos",
    "evidence": "Proyecto de prueba renombrado y desactivado; volver a dejar los datos de prueba como estaban",
    "limit": 60,
    "status": "Pendiente",
    "attempts": 0,
    "minutes": 0,
    "entrega": "E2",
    "fails": 0,
    "ready": false
   },
   {
    "id": "E2-07",
    "action": "En My Day: aviso \"N new folders to review\" con botón \"Review folders\" que lleva a Configuration. Solo visible si N > 0",
    "owner": "Agente",
    "depends": "E2-05",
    "expected": "Oscar se entera de carpetas nuevas",
    "evidence": "Aviso visible con una carpeta en Nueva y oculto con 0",
    "limit": 30,
    "status": "Pendiente",
    "attempts": 0,
    "minutes": 0,
    "entrega": "E2",
    "fails": 0,
    "ready": false
   },
   {
    "id": "E2-08",
    "action": "Cambiar el trigger de PFA_E2_LeerCarpetas a Recurrence diaria a las 4:00 a. m., zona Central Standard Time, y encender el flujo",
    "owner": "Agente",
    "depends": "E2-04",
    "expected": "Detección diaria de carpetas nuevas",
    "evidence": "Flujo encendido; \"Next run\" muestra 4:00 a. m. Central",
    "limit": 30,
    "status": "Pendiente",
    "attempts": 0,
    "minutes": 0,
    "entrega": "E2",
    "fails": 0,
    "ready": false
   },
   {
    "id": "E2-09",
    "action": "Guardar y publicar la app. En la app publicada, probar con la carpeta PFA-Prueba: Project, Change, Not a project, Change otra vez y Project; revisar el aviso de My Day y Deactivate en Projects. Dejar PFA-Prueba como Project al terminar",
    "owner": "Agente",
    "depends": "E2-07, E2-08",
    "expected": "Versión publicada y controles probados",
    "evidence": "Número de versión en worklog; cada botón probado con su efecto en la lista anotado",
    "limit": 30,
    "status": "Pendiente",
    "attempts": 0,
    "minutes": 0,
    "entrega": "E2",
    "fails": 0,
    "ready": false
   },
   {
    "id": "E2-10",
    "action": "Decidir en la app todas las carpetas de Projects (incluidas las subcarpetas de proyectos con varios proyectos dentro) y revisar la lista de proyectos",
    "owner": "Oscar",
    "depends": "E2-09",
    "expected": "Proyectos reales definidos",
    "evidence": "Oscar escribe \"E2 aceptada\"",
    "limit": 0,
    "status": "Pendiente",
    "attempts": 0,
    "minutes": 0,
    "entrega": "E2",
    "fails": 0,
    "ready": false
   }
  ],
  "E3": [
   {
    "id": "E3-01",
    "action": "Confirmar que la carpeta Projects/PFA-Prueba tiene 5 correos enviados por Oscar a sí mismo, sin datos de clientes, y que está marcada como proyecto en la app",
    "owner": "Oscar",
    "depends": "E2-10",
    "expected": "Carpeta de prueba lista",
    "evidence": "Oscar confirma",
    "limit": 0,
    "status": "Pendiente",
    "attempts": 0,
    "minutes": 0,
    "entrega": "E3",
    "fails": 0,
    "ready": false
   },
   {
    "id": "E3-02",
    "action": "En List settings de PFA_Messages: dejar como obligatorias solo InternetMessageId, OutlookMessageId, Subject, Sender, ReceivedSentUtc y FolderId. Anotar en worklog las columnas cambiadas",
    "owner": "Agente",
    "depends": "E2-10",
    "expected": "La lista acepta un correo con 6 campos",
    "evidence": "Columnas cambiadas anotadas en worklog",
    "limit": 30,
    "status": "Pendiente",
    "attempts": 0,
    "minutes": 0,
    "entrega": "E3",
    "fails": 0,
    "ready": false
   },
   {
    "id": "E3-03",
    "action": "Crear el flujo PFA_E3_CargarCorreos. Trigger manual con entrada opcional SoloCarpeta (texto). Pasos: Get items de PFA_MailFolders con Included = Sí (o solo la carpeta indicada) → por cada carpeta, Get emails (V3) de los últimos 30 días, Top 50, sin adjuntos → por cada correo, Get items en PFA_Messages por InternetMessageId → Create item o Update item. Llenar las 6 columnas obligatorias más OutlookWebLink y ObservedFolderPath. Ninguna acción que modifique el buzón (H-03)",
    "owner": "Agente",
    "depends": "E3-01, E3-02",
    "expected": "Flujo guardado",
    "evidence": "Flujo guardado; Flow Checker 0 errores",
    "limit": 90,
    "status": "Pendiente",
    "attempts": 0,
    "minutes": 0,
    "entrega": "E3",
    "fails": 0,
    "ready": false
   },
   {
    "id": "E3-04",
    "action": "Ejecutar el flujo con SoloCarpeta = PFA-Prueba, dos veces",
    "owner": "Agente",
    "depends": "E3-03",
    "expected": "5 correos sin duplicados",
    "evidence": "Las 2 corridas Succeeded; 5 filas de PFA-Prueba después de cada una",
    "limit": 30,
    "status": "Pendiente",
    "attempts": 0,
    "minutes": 0,
    "entrega": "E3",
    "fails": 0,
    "ready": false
   },
   {
    "id": "E3-05",
    "action": "Pantalla Projects (YAML): al seleccionar un proyecto, gallery con los correos de todas sus carpetas (propia y ParteDelSuperior), con asunto, remitente y fecha, ordenados por fecha descendente. Al tocar un correo, abrir OutlookWebLink con Launch()",
    "owner": "Agente",
    "depends": "E3-04",
    "expected": "Oscar ve los correos de cada proyecto",
    "evidence": "Los 5 correos visibles en PFA-Prueba",
    "limit": 90,
    "status": "Pendiente",
    "attempts": 0,
    "minutes": 0,
    "entrega": "E3",
    "fails": 0,
    "ready": false
   },
   {
    "id": "E3-06",
    "action": "Ejecutar el flujo sin SoloCarpeta (todas las carpetas activas)",
    "owner": "Agente",
    "depends": "E3-05",
    "expected": "Correos reales cargados",
    "evidence": "Run Succeeded; conteo de correos por carpeta en worklog, con carpetas numeradas y sin nombres",
    "limit": 30,
    "status": "Pendiente",
    "attempts": 0,
    "minutes": 0,
    "entrega": "E3",
    "fails": 0,
    "ready": false
   },
   {
    "id": "E3-07",
    "action": "Guardar y publicar la app. En la app publicada, abrir PFA-Prueba, ver sus 5 correos y abrir uno con el botón de Outlook",
    "owner": "Agente",
    "depends": "E3-06",
    "expected": "Versión publicada y controles probados",
    "evidence": "Número de versión en worklog; el correo abre en Outlook",
    "limit": 30,
    "status": "Pendiente",
    "attempts": 0,
    "minutes": 0,
    "entrega": "E3",
    "fails": 0,
    "ready": false
   },
   {
    "id": "E3-08",
    "action": "Abrir 2 proyectos en la app, revisar sus correos y abrir uno en Outlook",
    "owner": "Oscar",
    "depends": "E3-07",
    "expected": "Oscar usa la entrega",
    "evidence": "Oscar escribe \"E3 aceptada\"",
    "limit": 0,
    "status": "Pendiente",
    "attempts": 0,
    "minutes": 0,
    "entrega": "E3",
    "fails": 0,
    "ready": false
   }
  ],
  "T": [
   {
    "id": "T-01",
    "action": "Registrar el soporte hecho desde 2026-09-30: GitHub CLI, tablero, publicación, tareas programadas y revisor",
    "owner": "Agente",
    "depends": "—",
    "expected": "El trabajo previo queda atribuido a T sin duplicar horas históricas",
    "evidence": "7 filas del worklog reatribuidas desde E0-05–E0-08 a T-01; se conservan horas, resultados y resúmenes",
    "limit": 30,
    "status": "Hecha",
    "attempts": 7,
    "minutes": 41,
    "entrega": "T",
    "fails": 1
   },
   {
    "id": "T-02",
    "action": "Revisar la publicación cada 15 minutos, reconciliar el hueco del log y dejar registrada la causa",
    "owner": "Agente",
    "depends": "—",
    "expected": "El registro de publicaciones concuerda con los commits del tablero",
    "evidence": "Publicaciones 12:39 y 13:39 Central verificadas contra el clon y el sitio; causa documentada en KNOWN-FIXES.md",
    "limit": 30,
    "status": "Hecha",
    "attempts": 1,
    "minutes": 7,
    "entrega": "T",
    "fails": 0
   },
   {
    "id": "T-03",
    "action": "Aplicar los puntos B y C del pedido de Oscar: reglas, incidentes, lecciones, pendientes y publicación",
    "owner": "Agente",
    "depends": "—",
    "expected": "Los cinco incidentes quedan registrados y el tablero muestra el pendiente de E1-08",
    "evidence": "Archivos de control actualizados, automatizaciones alineadas, preview comprobado o bloqueo de login registrado, y tablero publicado",
    "limit": 90,
    "status": "Hecha",
    "attempts": 1,
    "minutes": 11,
    "entrega": "T",
    "fails": 0
   },
   {
    "id": "T-04",
    "action": "Integrar la skill planear y los cambios de procedimiento pedidos: rol de Oscar, recuperación del navegador, clasificación de hallazgos, política del tablero y estado/decisión de E1",
    "owner": "Agente",
    "depends": "—",
    "expected": "Reglas coherentes, tablero genera solo pendientes de Oscar y E1 continúa en el orden pedido",
    "evidence": "Skill y configuración presentes; reglas, incidentes y hallazgos actualizados; $heartbeatMinutes = 15; E1-08 Pendiente depende de E1-05; decisión de E1-10 registrada; tablero y commit actualizados",
    "limit": 90,
    "status": "Hecha",
    "attempts": 1,
    "minutes": 19,
    "entrega": "T",
    "fails": 0
   }
  ]
 },
 "nextTask": {
  "id": "E1-05",
  "action": "Reabrir My Day y Diagnostics: eliminar los encabezados/títulos duplicados o viejos. Dejar en ambas el bloque común idéntico; mover Refresh de My Day fuera del encabezado y conservar su acción",
  "owner": "Agente",
  "depends": "E1-04",
  "expected": "2 pantallas con un solo encabezado estándar",
  "evidence": "Vista previa; árbol de controles sin encabezado duplicado; menú navega a las 7 pantallas; Refresh funciona",
  "limit": 60,
  "status": "En curso",
  "attempts": 5,
  "minutes": 34,
  "entrega": "E1",
  "fails": 0,
  "ready": true
 },
 "upcoming": [
  {
   "id": "E1-05",
   "action": "Reabrir My Day y Diagnostics: eliminar los encabezados/títulos duplicados o viejos. Dejar en ambas el bloque común idéntico; mover Refresh de My Day fuera del encabezado y conservar su acción",
   "owner": "Agente",
   "depends": "E1-04",
   "expected": "2 pantallas con un solo encabezado estándar",
   "evidence": "Vista previa; árbol de controles sin encabezado duplicado; menú navega a las 7 pantallas; Refresh funciona",
   "limit": 60,
   "status": "En curso",
   "attempts": 5,
   "minutes": 34,
   "entrega": "E1",
   "fails": 0,
   "ready": true
  },
  {
   "id": "E1-08",
   "action": "Revisar las 7 pantallas en vista previa de escritorio, teléfono vertical y iPad horizontal. Guardar y publicar. En la app publicada, probar la navegación desde 2 pantallas distintas en formato horizontal",
   "owner": "Agente",
   "depends": "E1-05",
   "expected": "Versión publicada y pantallas adaptadas",
   "evidence": "Número de versión en worklog; las 7 pantallas se adaptan a cada formato y las 7 opciones navegan y marcan el activo correcto en horizontal",
   "limit": 45,
   "status": "Pendiente",
   "attempts": 2,
   "minutes": 22,
   "entrega": "E1",
   "fails": 0,
   "ready": false
  },
  {
   "id": "E1-09",
   "action": "Recorrer las 7 pantallas en la app publicada después de E1-10",
   "owner": "Oscar",
   "depends": "E1-10",
   "expected": "Oscar acepta el estándar visual y la navegación vertical",
   "evidence": "Oscar escribe \"E1 aceptada\" o pide cambios concretos",
   "limit": 0,
   "status": "Pendiente",
   "attempts": 0,
   "minutes": 0,
   "entrega": "E1",
   "fails": 0,
   "ready": false
  },
  {
   "id": "E1-10",
   "action": "Adaptar el encabezado común en las 7 pantallas: botones horizontales en escritorio e iPad horizontal; en teléfono e iPad vertical, un botón de menú que abre una lista seleccionable con las 7 pantallas y marca la activa",
   "owner": "Agente",
   "depends": "E1-08",
   "expected": "Navegación usable sin barra horizontal en formato vertical",
   "evidence": "YAML común aplicado en las 7 pantallas; vista previa y app publicada confirman selector en vertical y botones en horizontal; las 7 opciones navegan",
   "limit": 60,
   "status": "Pendiente",
   "attempts": 0,
   "minutes": 0,
   "entrega": "E1",
   "fails": 0,
   "ready": false
  },
  {
   "id": "E2-01",
   "action": "En List settings de PFA_MailFolders y PFA_Projects: anotar el tipo real de cada columna. Dejar obligatorias solo OutlookFolderId y FolderName (MailFolders) y ProjectId y OfficialName (Projects). Agregar a PFA_MailFolders la columna de texto Decision con valor por defecto Nueva. Confirmar que existen ParentFolderId y DisplayedPath. Anotar en worklog todo lo cambiado",
   "owner": "Agente",
   "depends": "E1-09",
   "expected": "Listas listas para carpetas y proyectos",
   "evidence": "Tabla de columnas y cambios en worklog",
   "limit": 30,
   "status": "Pendiente",
   "attempts": 0,
   "minutes": 0,
   "entrega": "E2",
   "fails": 0,
   "ready": false
  },
  {
   "id": "E2-02",
   "action": "Crear el flujo PFA_E2_LeerCarpetas en la solución PFA Pilot, con trigger manual. Pasos: Send an HTTP request (Office 365 Outlook) para encontrar la carpeta Projects dentro de Inbox → leer sus subcarpetas de nivel 1 (KF-06) → por cada una, Get items en PFA_MailFolders por OutlookFolderId → si no existe, Create item con Decision = Nueva, Included = No, ParentFolderId y DisplayedPath (ruta desde Projects); si existe, Update item solo de FolderName, DisplayedPath y LastEnumeratedUtc. Nunca cambiar Decision, Included ni ProjectId de una fila existente",
   "owner": "Agente",
   "depends": "E2-01",
   "expected": "Flujo de nivel 1 guardado",
   "evidence": "Flujo guardado; Flow Checker 0 errores",
   "limit": 90,
   "status": "Pendiente",
   "attempts": 0,
   "minutes": 0,
   "entrega": "E2",
   "fails": 0,
   "ready": false
  },
  {
   "id": "E2-03",
   "action": "Ejecutar el flujo una vez",
   "owner": "Agente",
   "depends": "E2-02",
   "expected": "Una fila por carpeta de nivel 1",
   "evidence": "Run Succeeded; número de filas igual al de carpetas de nivel 1 (anotar el número)",
   "limit": 20,
   "status": "Pendiente",
   "attempts": 0,
   "minutes": 0,
   "entrega": "E2",
   "fails": 0,
   "ready": false
  },
  {
   "id": "E2-04",
   "action": "Agregar al flujo los niveles 2 y 3 (subcarpetas de cada carpeta leída). Ejecutar 2 veces. Luego cambiar a mano una fila a Decision = NoEsProyecto y ejecutar otra vez",
   "owner": "Agente",
   "depends": "E2-03",
   "expected": "Todas las carpetas de Projects, sin duplicados y sin perder decisiones",
   "evidence": "Mismo número de filas en las 3 corridas; la fila cambiada conserva su decisión (devolverla a Nueva al terminar)",
   "limit": 60,
   "status": "Pendiente",
   "attempts": 0,
   "minutes": 0,
   "entrega": "E2",
   "fails": 0,
   "ready": false
  },
  {
   "id": "E2-05",
   "action": "Pantalla Configuration (YAML en design/yaml/configuracion.pa.yaml, estándar de DISENO.md). Sección \"New folders to review (N)\": carpetas con Decision = Nueva, con su ruta y 3 botones. **Project**: crea el proyecto en PFA_Projects (ProjectId generado, OfficialName = nombre de la carpeta, Status = Active, ConfirmationStatus = Confirmed, PrimaryOutlookFolderId) o reactiva el que ya tenía, y guarda en la carpeta Decision = Proyecto, Included = Sí y ProjectId. **Part of parent project**: Decision = ParteDelSuperior, Included = Sí, ProjectId del ancestro más cercano con Decision = Proyecto (botón desactivado si no hay ninguno). **Not a project**: Decision = NoEsProyecto, Included = No. Una carpeta con subcarpetas se puede manejar de dos formas: la carpeta padre como Project y sus subcarpetas como Part of parent project (un solo proyecto), o la carpeta padre como Not a project y cada subcarpeta como Project (proyectos independientes). Las carpetas se muestran ordenadas por ruta para que las subcarpetas queden debajo de su carpeta padre. Sección \"Reviewed folders\": ruta, decisión y botón \"Change\" que la devuelve a Nueva. Nunca borrar filas",
   "owner": "Agente",
   "depends": "E2-04",
   "expected": "Oscar decide sus carpetas desde la app",
   "evidence": "Prueba con 3 carpetas, una por opción; \"Change\" funciona; no se crean proyectos duplicados",
   "limit": 90,
   "status": "Pendiente",
   "attempts": 0,
   "minutes": 0,
   "entrega": "E2",
   "fails": 0,
   "ready": false
  },
  {
   "id": "E2-06",
   "action": "Pantalla Projects (YAML design/yaml/proyectos.pa.yaml): gallery con los proyectos Status = Active, nombre editable, número de carpetas asociadas y botón \"Deactivate\" (proyecto Inactive y sus carpetas Included = No). Los proyectos activos se muestran agrupados por su carpeta padre cuando la tienen",
   "owner": "Agente",
   "depends": "E2-05",
   "expected": "Oscar ve y ajusta sus proyectos",
   "evidence": "Proyecto de prueba renombrado y desactivado; volver a dejar los datos de prueba como estaban",
   "limit": 60,
   "status": "Pendiente",
   "attempts": 0,
   "minutes": 0,
   "entrega": "E2",
   "fails": 0,
   "ready": false
  },
  {
   "id": "E2-07",
   "action": "En My Day: aviso \"N new folders to review\" con botón \"Review folders\" que lleva a Configuration. Solo visible si N > 0",
   "owner": "Agente",
   "depends": "E2-05",
   "expected": "Oscar se entera de carpetas nuevas",
   "evidence": "Aviso visible con una carpeta en Nueva y oculto con 0",
   "limit": 30,
   "status": "Pendiente",
   "attempts": 0,
   "minutes": 0,
   "entrega": "E2",
   "fails": 0,
   "ready": false
  },
  {
   "id": "E2-08",
   "action": "Cambiar el trigger de PFA_E2_LeerCarpetas a Recurrence diaria a las 4:00 a. m., zona Central Standard Time, y encender el flujo",
   "owner": "Agente",
   "depends": "E2-04",
   "expected": "Detección diaria de carpetas nuevas",
   "evidence": "Flujo encendido; \"Next run\" muestra 4:00 a. m. Central",
   "limit": 30,
   "status": "Pendiente",
   "attempts": 0,
   "minutes": 0,
   "entrega": "E2",
   "fails": 0,
   "ready": false
  },
  {
   "id": "E2-09",
   "action": "Guardar y publicar la app. En la app publicada, probar con la carpeta PFA-Prueba: Project, Change, Not a project, Change otra vez y Project; revisar el aviso de My Day y Deactivate en Projects. Dejar PFA-Prueba como Project al terminar",
   "owner": "Agente",
   "depends": "E2-07, E2-08",
   "expected": "Versión publicada y controles probados",
   "evidence": "Número de versión en worklog; cada botón probado con su efecto en la lista anotado",
   "limit": 30,
   "status": "Pendiente",
   "attempts": 0,
   "minutes": 0,
   "entrega": "E2",
   "fails": 0,
   "ready": false
  },
  {
   "id": "E2-10",
   "action": "Decidir en la app todas las carpetas de Projects (incluidas las subcarpetas de proyectos con varios proyectos dentro) y revisar la lista de proyectos",
   "owner": "Oscar",
   "depends": "E2-09",
   "expected": "Proyectos reales definidos",
   "evidence": "Oscar escribe \"E2 aceptada\"",
   "limit": 0,
   "status": "Pendiente",
   "attempts": 0,
   "minutes": 0,
   "entrega": "E2",
   "fails": 0,
   "ready": false
  },
  {
   "id": "E3-01",
   "action": "Confirmar que la carpeta Projects/PFA-Prueba tiene 5 correos enviados por Oscar a sí mismo, sin datos de clientes, y que está marcada como proyecto en la app",
   "owner": "Oscar",
   "depends": "E2-10",
   "expected": "Carpeta de prueba lista",
   "evidence": "Oscar confirma",
   "limit": 0,
   "status": "Pendiente",
   "attempts": 0,
   "minutes": 0,
   "entrega": "E3",
   "fails": 0,
   "ready": false
  }
 ],
 "doneTasks": [
  {
   "id": "E0-01",
   "action": "Hacer commit de todo el estado actual del repositorio, incluidos los archivos recién copiados, antes de cualquier otro cambio. Mensaje: E0-01 línea base antes de reestructuración",
   "owner": "Agente",
   "depends": "—",
   "expected": "Los cambios pendientes desde el 19-sep quedan guardados en git",
   "evidence": "Hash del commit anotado en worklog",
   "limit": 15,
   "status": "Hecha",
   "attempts": 1,
   "minutes": 0,
   "entrega": "E0",
   "fails": 0
  },
  {
   "id": "E0-02",
   "action": "Verificar que existen AGENTS.md, control/, design/, dashboard/ y tools/build_dashboard.py y tools/publish_dashboard.ps1",
   "owner": "Agente",
   "depends": "E0-01",
   "expected": "Archivos instalados",
   "evidence": "git status limpio después del commit E0-02",
   "limit": 10,
   "status": "Hecha",
   "attempts": 1,
   "minutes": 0,
   "entrega": "E0",
   "fails": 0
  },
  {
   "id": "E0-03",
   "action": "Agregar al inicio de README.md, deployment/current-status.md, deployment/project-traceability-register.md y deployment/execution-ledger.md esta línea: > Congelado el 2026-09-30. El estado vigente está en control/STATUS.md y las reglas en AGENTS.md.",
   "owner": "Agente",
   "depends": "E0-02",
   "expected": "Nadie usa esos archivos como fuente vigente",
   "evidence": "Los 4 archivos empiezan con el aviso",
   "limit": 10,
   "status": "Hecha",
   "attempts": 1,
   "minutes": 1,
   "entrega": "E0",
   "fails": 0
  },
  {
   "id": "E0-04",
   "action": "Comprobar con Import-Csv control/worklog.csv que el archivo tiene 11 columnas y las líneas de E0-01 a E0-03 con horas reales",
   "owner": "Agente",
   "depends": "E0-03",
   "expected": "El registro de tiempo funciona",
   "evidence": "Import-Csv lee 3 filas sin error; resultado anotado en worklog. No requiere Excel ni validación de Oscar",
   "limit": 10,
   "status": "Hecha",
   "attempts": 2,
   "minutes": 1,
   "entrega": "E0",
   "fails": 0
  },
  {
   "id": "E0-05",
   "action": "Programar en Codex el revisor (control/REVISOR.md) todos los días a las 4:30 a. m. y 5:00 p. m. hora Central. Ejecutarlo una vez a mano",
   "owner": "Ambos",
   "depends": "E0-04",
   "expected": "El revisor corre solo 2 veces al día",
   "evidence": "control/REVISION.md generado; Oscar ve las 2 tareas programadas en Codex",
   "limit": 20,
   "status": "Hecha",
   "attempts": 1,
   "minutes": 0,
   "entrega": "E0",
   "fails": 0
  },
  {
   "id": "E0-06",
   "action": "Comprobar gh --version; si falta, descargar el ZIP portable oficial de GitHub CLI, extraerlo en %LOCALAPPDATA%\\Programs\\gh y agregar bin al PATH de usuario. Oscar ejecuta gh auth login; después el Agente ejecuta gh auth setup-git",
   "owner": "Ambos",
   "depends": "E0-02",
   "expected": "El computador puede publicar en GitHub sin depender de la cuenta de ChatGPT",
   "evidence": "gh auth status muestra la cuenta de Oscar y gh auth setup-git termina correctamente",
   "limit": 20,
   "status": "Hecha",
   "attempts": 4,
   "minutes": 0,
   "entrega": "E0",
   "fails": 0
  },
  {
   "id": "E0-07",
   "action": "Crear el repositorio público pfa-tablero (gh repo create pfa-tablero --public --add-readme), clonarlo en C:\\Users\\oscar\\Documents\\Puffer\\pfa-tablero, activar GitHub Pages desde la rama main, carpeta raíz, y completar dashboard/config.json con owner, repo, pagesUrl y publishClone",
   "owner": "Agente",
   "depends": "E0-06",
   "expected": "Sitio del tablero creado",
   "evidence": "La URL de Pages responde (aunque esté vacía)",
   "limit": 30,
   "status": "Hecha",
   "attempts": 1,
   "minutes": 0,
   "entrega": "E0",
   "fails": 0
  },
  {
   "id": "E0-08",
   "action": "Ejecutar pwsh -File tools/publish_dashboard.ps1 una vez. Registrar en el Programador de tareas de Windows la tarea PFA Tablero que ejecuta ese script cada hora (instrucciones dentro del script)",
   "owner": "Agente",
   "depends": "E0-07",
   "expected": "El tablero se publica solo cada hora",
   "evidence": "La URL muestra E0 con los datos actuales; Get-ScheduledTask -TaskName \"PFA Tablero\" existe y su última ejecución fue correcta",
   "limit": 30,
   "status": "Hecha",
   "attempts": 1,
   "minutes": 0,
   "entrega": "E0",
   "fails": 0
  },
  {
   "id": "E0-09",
   "action": "Abrir la URL del tablero en el celular y en el computador de Puffer. Tocar \"Responder\" en un pendiente y enviar el issue que se abre",
   "owner": "Oscar",
   "depends": "E0-08",
   "expected": "Oscar ve el tablero y responde desde él",
   "evidence": "El agente procesa el issue en la sesión siguiente; Oscar escribe \"E0 aceptada\"",
   "limit": 0,
   "status": "Hecha",
   "attempts": 1,
   "minutes": 1,
   "entrega": "E0",
   "fails": 0
  },
  {
   "id": "E1-01",
   "action": "En la app PFA Diagnostics Test: en la pantalla Diagnostics, clic derecho en el encabezado y en el contenedor de la tabla → \"View code\" → \"Copy code\". Guardar cada bloque en design/referencia/ (encabezado.pa.yaml, tabla.pa.yaml). No modificar esa app",
   "owner": "Agente",
   "depends": "E0-02",
   "expected": "Referencia visual guardada como código",
   "evidence": "2 archivos en design/referencia/ con las versiones de control anotadas",
   "limit": 20,
   "status": "Hecha",
   "attempts": 1,
   "minutes": 10,
   "entrega": "E1",
   "fails": 0
  },
  {
   "id": "E1-02",
   "action": "Comparar la referencia con design/DISENO.md y design/tema.fx. Ajustar los valores del tema (colores, tamaños, fuentes) a los reales de la referencia. Completar la sección \"Versiones de control\" de DISENO.md",
   "owner": "Agente",
   "depends": "E1-01",
   "expected": "Tema alineado con la referencia",
   "evidence": "Diferencias anotadas en worklog; tema.fx actualizado",
   "limit": 30,
   "status": "Hecha",
   "attempts": 1,
   "minutes": 6,
   "entrega": "E1",
   "fails": 0
  },
  {
   "id": "E1-03",
   "action": "Pegar el contenido de design/tema.fx en la propiedad Formulas del objeto App de PFA_Pilot_App",
   "owner": "Agente",
   "depends": "E1-02",
   "expected": "Tema y menú disponibles en toda la app",
   "evidence": "\"No formula errors\"; app guardada",
   "limit": 20,
   "status": "Hecha",
   "attempts": 1,
   "minutes": 2,
   "entrega": "E1",
   "fails": 0
  },
  {
   "id": "E1-04",
   "action": "Escribir design/yaml/encabezado.pa.yaml y design/yaml/titulo-pagina.pa.yaml según DISENO.md (encabezado con gallery horizontal sobre Nav). Crear con ellos una pantalla de prueba scrPlantilla pegando un bloque Screens:",
   "owner": "Agente",
   "depends": "E1-03",
   "expected": "Plantilla funcionando",
   "evidence": "Vista previa de scrPlantilla igual al estándar, en escritorio y teléfono",
   "limit": 90,
   "status": "Hecha",
   "attempts": 1,
   "minutes": 13,
   "entrega": "E1",
   "fails": 0
  },
  {
   "id": "E1-06",
   "action": "Igual que E1-05 en Projects, Tasks y Review",
   "owner": "Agente",
   "depends": "E1-05",
   "expected": "5 pantallas con el estándar",
   "evidence": "Vista previa correcta",
   "limit": 60,
   "status": "Hecha",
   "attempts": 1,
   "minutes": 24,
   "entrega": "E1",
   "fails": 0
  },
  {
   "id": "E1-07",
   "action": "Igual que E1-05 en Historical Search y Configuration. Borrar scrPlantilla",
   "owner": "Agente",
   "depends": "E1-06",
   "expected": "7 pantallas con el estándar",
   "evidence": "Vista previa correcta; scrPlantilla eliminada",
   "limit": 60,
   "status": "Hecha",
   "attempts": 2,
   "minutes": 29,
   "entrega": "E1",
   "fails": 0
  },
  {
   "id": "T-01",
   "action": "Registrar el soporte hecho desde 2026-09-30: GitHub CLI, tablero, publicación, tareas programadas y revisor",
   "owner": "Agente",
   "depends": "—",
   "expected": "El trabajo previo queda atribuido a T sin duplicar horas históricas",
   "evidence": "7 filas del worklog reatribuidas desde E0-05–E0-08 a T-01; se conservan horas, resultados y resúmenes",
   "limit": 30,
   "status": "Hecha",
   "attempts": 7,
   "minutes": 41,
   "entrega": "T",
   "fails": 1
  },
  {
   "id": "T-02",
   "action": "Revisar la publicación cada 15 minutos, reconciliar el hueco del log y dejar registrada la causa",
   "owner": "Agente",
   "depends": "—",
   "expected": "El registro de publicaciones concuerda con los commits del tablero",
   "evidence": "Publicaciones 12:39 y 13:39 Central verificadas contra el clon y el sitio; causa documentada en KNOWN-FIXES.md",
   "limit": 30,
   "status": "Hecha",
   "attempts": 1,
   "minutes": 7,
   "entrega": "T",
   "fails": 0
  },
  {
   "id": "T-03",
   "action": "Aplicar los puntos B y C del pedido de Oscar: reglas, incidentes, lecciones, pendientes y publicación",
   "owner": "Agente",
   "depends": "—",
   "expected": "Los cinco incidentes quedan registrados y el tablero muestra el pendiente de E1-08",
   "evidence": "Archivos de control actualizados, automatizaciones alineadas, preview comprobado o bloqueo de login registrado, y tablero publicado",
   "limit": 90,
   "status": "Hecha",
   "attempts": 1,
   "minutes": 11,
   "entrega": "T",
   "fails": 0
  },
  {
   "id": "T-04",
   "action": "Integrar la skill planear y los cambios de procedimiento pedidos: rol de Oscar, recuperación del navegador, clasificación de hallazgos, política del tablero y estado/decisión de E1",
   "owner": "Agente",
   "depends": "—",
   "expected": "Reglas coherentes, tablero genera solo pendientes de Oscar y E1 continúa en el orden pedido",
   "evidence": "Skill y configuración presentes; reglas, incidentes y hallazgos actualizados; $heartbeatMinutes = 15; E1-08 Pendiente depende de E1-05; decisión de E1-10 registrada; tablero y commit actualizados",
   "limit": 90,
   "status": "Hecha",
   "attempts": 1,
   "minutes": 19,
   "entrega": "T",
   "fails": 0
  }
 ],
 "alerts": [],
 "kpi": {
  "tasksDone": 19,
  "tasksTotal": 41,
  "entregasAccepted": 1,
  "entregasTotal": 12,
  "time": {
   "prod": 221,
   "unprod": 0,
   "wait": 6,
   "total": 227
  },
  "last24h": {
   "prod": 221,
   "unprod": 0,
   "wait": 6,
   "total": 227
  },
  "last7d": {
   "prod": 221,
   "unprod": 0,
   "wait": 6,
   "total": 227
  },
  "product": {
   "prod": 143,
   "unprod": 0,
   "wait": 4,
   "total": 147
  },
  "support": {
   "prod": 78,
   "unprod": 0,
   "wait": 2,
   "total": 80
  }
 },
 "days": [
  {
   "date": "2026-09-18",
   "prod": 0,
   "unprod": 0,
   "wait": 0
  },
  {
   "date": "2026-09-19",
   "prod": 0,
   "unprod": 0,
   "wait": 0
  },
  {
   "date": "2026-09-20",
   "prod": 0,
   "unprod": 0,
   "wait": 0
  },
  {
   "date": "2026-09-21",
   "prod": 0,
   "unprod": 0,
   "wait": 0
  },
  {
   "date": "2026-09-22",
   "prod": 0,
   "unprod": 0,
   "wait": 0
  },
  {
   "date": "2026-09-23",
   "prod": 0,
   "unprod": 0,
   "wait": 0
  },
  {
   "date": "2026-09-24",
   "prod": 0,
   "unprod": 0,
   "wait": 0
  },
  {
   "date": "2026-09-25",
   "prod": 0,
   "unprod": 0,
   "wait": 0
  },
  {
   "date": "2026-09-26",
   "prod": 0,
   "unprod": 0,
   "wait": 0
  },
  {
   "date": "2026-09-27",
   "prod": 0,
   "unprod": 0,
   "wait": 0
  },
  {
   "date": "2026-09-28",
   "prod": 0,
   "unprod": 0,
   "wait": 0
  },
  {
   "date": "2026-09-29",
   "prod": 0,
   "unprod": 0,
   "wait": 0
  },
  {
   "date": "2026-09-30",
   "prod": 202,
   "unprod": 0,
   "wait": 6
  },
  {
   "date": "2026-10-01",
   "prod": 19,
   "unprod": 0,
   "wait": 0
  }
 ],
 "categories": [
  {
   "category": "AUTH",
   "minutes": 0,
   "attempts": 1
  }
 ],
 "waits": [
  {
   "category": "AUTH",
   "minutes": 4
  },
  {
   "category": "NAVEGADOR",
   "minutes": 2
  }
 ],
 "topTasks": [
  {
   "task": "T-01",
   "prod": 41,
   "unprod": 0,
   "wait": 0,
   "total": 41
  },
  {
   "task": "E1-05",
   "prod": 34,
   "unprod": 0,
   "wait": 0,
   "total": 34
  },
  {
   "task": "E1-07",
   "prod": 29,
   "unprod": 0,
   "wait": 0,
   "total": 29
  },
  {
   "task": "E1-08",
   "prod": 22,
   "unprod": 0,
   "wait": 4,
   "total": 26
  },
  {
   "task": "E1-06",
   "prod": 24,
   "unprod": 0,
   "wait": 0,
   "total": 24
  },
  {
   "task": "T-04",
   "prod": 19,
   "unprod": 0,
   "wait": 0,
   "total": 19
  },
  {
   "task": "E1-04",
   "prod": 13,
   "unprod": 0,
   "wait": 0,
   "total": 13
  },
  {
   "task": "T-03",
   "prod": 11,
   "unprod": 0,
   "wait": 2,
   "total": 13
  },
  {
   "task": "E1-01",
   "prod": 10,
   "unprod": 0,
   "wait": 0,
   "total": 10
  },
  {
   "task": "T-02",
   "prod": 7,
   "unprod": 0,
   "wait": 0,
   "total": 7
  }
 ],
 "byAccount": [
  {
   "account": "personal",
   "minutes": 227
  }
 ],
 "recent": [
  {
   "start": "2026-10-01T00:58:00Z",
   "minutes": 0,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-05",
   "attempt": 5,
   "result": "AVANCE",
   "kind": "prod",
   "category": "DISENO",
   "summary": "Comprobé el YAML local de My Day después de mover Refresh fuera del encabezado común",
   "evidence": "Un btnDashboardRefresh con la acción intacta y sin Y duplicada; Studio sigue en solo lectura por otra sesión, así que falta aplicar y probar"
  },
  {
   "start": "2026-10-01T00:37:00Z",
   "minutes": 19,
   "account": "personal",
   "entrega": "T",
   "task": "T-04",
   "attempt": 1,
   "result": "HECHA",
   "kind": "prod",
   "category": "OTRO",
   "summary": "Se actualizaron reglas, hallazgos, estados, decisión E1-10 y filtro del tablero; se revalidó E0-04",
   "evidence": "Skill/config presentes; Import-Csv: 11 columnas y filas E0-01 a E0-03 con horas; index.html y data.js confirmados en main; escritura del log local denegada"
  },
  {
   "start": "2026-09-30T22:40:00Z",
   "minutes": 4,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-05",
   "attempt": 4,
   "result": "AVANCE",
   "kind": "prod",
   "category": "DISENO",
   "summary": "Separé Refresh del encabezado y preparé el selector de navegación para formato vertical.",
   "evidence": "Un encabezado y Refresh fuera de él en YAML; selector común y DISENO actualizados. Falta aplicar y validar en Studio; dos lecturas del navegador expiraron. La publicación del tablero falló al escribir el log y no se reintentó."
  },
  {
   "start": "2026-09-30T22:00:00Z",
   "minutes": 0,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-08",
   "attempt": 2,
   "result": "ESPERA",
   "kind": "wait",
   "category": "NAVEGADOR",
   "summary": "Interrumpí las pruebas al repetirse dos veces el error de nodo desconectado en navegación.",
   "evidence": "Pestaña de la app publicada abierta; solicito recargarla en Edge y continuar cuando esté lista."
  },
  {
   "start": "2026-09-30T21:53:00Z",
   "minutes": 7,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-08",
   "attempt": 2,
   "result": "AVANCE",
   "kind": "prod",
   "category": "NAVEGADOR",
   "summary": "La app publicada abrió y navegó por My Day, Projects, Tasks, Review y Configuration; dos interacciones devolvieron el nodo desconectado.",
   "evidence": "La versión publicada está activa; falta completar las rutas y comprobar el resaltado del menú tras recuperar el navegador."
  },
  {
   "start": "2026-09-30T19:34:00Z",
   "minutes": 2,
   "account": "personal",
   "entrega": "T",
   "task": "T-03",
   "attempt": 1,
   "result": "ESPERA",
   "kind": "wait",
   "category": "NAVEGADOR",
   "summary": "Esperé a que GitHub Pages sirviera el último data.js después de que el build reportara estado built",
   "evidence": "El data.js con T-03 de 11 min y el pendiente E1-08 respondió HTTP 200"
  },
  {
   "start": "2026-09-30T19:23:00Z",
   "minutes": 11,
   "account": "personal",
   "entrega": "T",
   "task": "T-03",
   "attempt": 1,
   "result": "HECHA",
   "kind": "prod",
   "category": "DOCUMENTACION",
   "summary": "Apliqué B y C: reglas, incidentes y lecciones; registré el inicio de sesión pendiente y publiqué el tablero",
   "evidence": "INC-01 a INC-05 registrados; KF-P01 a KF-P05 y KF-H01 documentados; STATUS contiene E1-08; preview pendiente de Oscar; página HTTP 200"
  },
  {
   "start": "2026-09-30T19:16:00Z",
   "minutes": 7,
   "account": "personal",
   "entrega": "T",
   "task": "T-02",
   "attempt": 1,
   "result": "HECHA",
   "kind": "prod",
   "category": "OTRO",
   "summary": "Tarea Windows y página verificadas; concilié las dos publicaciones faltantes y registré que la pausa fue por la regla restrictiva del revisor",
   "evidence": "LastTaskResult 0; ruta absoluta pwsh; commits ef94990 y 7f3c40b en origin/main; página HTTP 200; log conciliado"
  },
  {
   "start": "2026-09-30T13:36:00Z",
   "minutes": 4,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-08",
   "attempt": 1,
   "result": "ESPERA",
   "kind": "wait",
   "category": "AUTH",
   "summary": "Power Apps solicitó iniciar sesión por expiración de sesión; se pausa la edición hasta que Oscar complete el acceso",
   "evidence": "AADSTS70044; botón Sign in visible en la pestaña PFA_Pilot_App"
  },
  {
   "start": "2026-09-30T13:21:00Z",
   "minutes": 15,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-08",
   "attempt": 1,
   "result": "AVANCE",
   "kind": "prod",
   "category": "DISENO",
   "summary": "Revisé las 7 pantallas en vista previa de escritorio y teléfono y probé los 7 botones del menú desde Projects y My Day; preparé el ajuste de ancho de botones en Configuration",
   "evidence": "Los 14 recorridos llegaron a la pantalla correcta y el activo se resaltó; Configuration conserva un recorte de texto en escritorio; app sin publicar; falta aplicar el ajuste preparado en Studio"
  }
 ],
 "history": [
  {
   "start": "2026-10-01T00:58:00Z",
   "minutes": 0,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-05",
   "attempt": 5,
   "result": "AVANCE",
   "kind": "prod",
   "category": "DISENO",
   "summary": "Comprobé el YAML local de My Day después de mover Refresh fuera del encabezado común",
   "evidence": "Un btnDashboardRefresh con la acción intacta y sin Y duplicada; Studio sigue en solo lectura por otra sesión, así que falta aplicar y probar"
  },
  {
   "start": "2026-10-01T00:37:00Z",
   "minutes": 19,
   "account": "personal",
   "entrega": "T",
   "task": "T-04",
   "attempt": 1,
   "result": "HECHA",
   "kind": "prod",
   "category": "OTRO",
   "summary": "Se actualizaron reglas, hallazgos, estados, decisión E1-10 y filtro del tablero; se revalidó E0-04",
   "evidence": "Skill/config presentes; Import-Csv: 11 columnas y filas E0-01 a E0-03 con horas; index.html y data.js confirmados en main; escritura del log local denegada"
  },
  {
   "start": "2026-09-30T22:40:00Z",
   "minutes": 4,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-05",
   "attempt": 4,
   "result": "AVANCE",
   "kind": "prod",
   "category": "DISENO",
   "summary": "Separé Refresh del encabezado y preparé el selector de navegación para formato vertical.",
   "evidence": "Un encabezado y Refresh fuera de él en YAML; selector común y DISENO actualizados. Falta aplicar y validar en Studio; dos lecturas del navegador expiraron. La publicación del tablero falló al escribir el log y no se reintentó."
  },
  {
   "start": "2026-09-30T22:00:00Z",
   "minutes": 0,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-08",
   "attempt": 2,
   "result": "ESPERA",
   "kind": "wait",
   "category": "NAVEGADOR",
   "summary": "Interrumpí las pruebas al repetirse dos veces el error de nodo desconectado en navegación.",
   "evidence": "Pestaña de la app publicada abierta; solicito recargarla en Edge y continuar cuando esté lista."
  },
  {
   "start": "2026-09-30T21:53:00Z",
   "minutes": 7,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-08",
   "attempt": 2,
   "result": "AVANCE",
   "kind": "prod",
   "category": "NAVEGADOR",
   "summary": "La app publicada abrió y navegó por My Day, Projects, Tasks, Review y Configuration; dos interacciones devolvieron el nodo desconectado.",
   "evidence": "La versión publicada está activa; falta completar las rutas y comprobar el resaltado del menú tras recuperar el navegador."
  },
  {
   "start": "2026-09-30T19:34:00Z",
   "minutes": 2,
   "account": "personal",
   "entrega": "T",
   "task": "T-03",
   "attempt": 1,
   "result": "ESPERA",
   "kind": "wait",
   "category": "NAVEGADOR",
   "summary": "Esperé a que GitHub Pages sirviera el último data.js después de que el build reportara estado built",
   "evidence": "El data.js con T-03 de 11 min y el pendiente E1-08 respondió HTTP 200"
  },
  {
   "start": "2026-09-30T19:23:00Z",
   "minutes": 11,
   "account": "personal",
   "entrega": "T",
   "task": "T-03",
   "attempt": 1,
   "result": "HECHA",
   "kind": "prod",
   "category": "DOCUMENTACION",
   "summary": "Apliqué B y C: reglas, incidentes y lecciones; registré el inicio de sesión pendiente y publiqué el tablero",
   "evidence": "INC-01 a INC-05 registrados; KF-P01 a KF-P05 y KF-H01 documentados; STATUS contiene E1-08; preview pendiente de Oscar; página HTTP 200"
  },
  {
   "start": "2026-09-30T19:16:00Z",
   "minutes": 7,
   "account": "personal",
   "entrega": "T",
   "task": "T-02",
   "attempt": 1,
   "result": "HECHA",
   "kind": "prod",
   "category": "OTRO",
   "summary": "Tarea Windows y página verificadas; concilié las dos publicaciones faltantes y registré que la pausa fue por la regla restrictiva del revisor",
   "evidence": "LastTaskResult 0; ruta absoluta pwsh; commits ef94990 y 7f3c40b en origin/main; página HTTP 200; log conciliado"
  },
  {
   "start": "2026-09-30T13:36:00Z",
   "minutes": 4,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-08",
   "attempt": 1,
   "result": "ESPERA",
   "kind": "wait",
   "category": "AUTH",
   "summary": "Power Apps solicitó iniciar sesión por expiración de sesión; se pausa la edición hasta que Oscar complete el acceso",
   "evidence": "AADSTS70044; botón Sign in visible en la pestaña PFA_Pilot_App"
  },
  {
   "start": "2026-09-30T13:21:00Z",
   "minutes": 15,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-08",
   "attempt": 1,
   "result": "AVANCE",
   "kind": "prod",
   "category": "DISENO",
   "summary": "Revisé las 7 pantallas en vista previa de escritorio y teléfono y probé los 7 botones del menú desde Projects y My Day; preparé el ajuste de ancho de botones en Configuration",
   "evidence": "Los 14 recorridos llegaron a la pantalla correcta y el activo se resaltó; Configuration conserva un recorte de texto en escritorio; app sin publicar; falta aplicar el ajuste preparado en Studio"
  },
  {
   "start": "2026-09-30T13:12:00Z",
   "minutes": 9,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-07",
   "attempt": 2,
   "result": "HECHA",
   "kind": "prod",
   "category": "DISENO",
   "summary": "Ajusté la galería móvil con botones apilados y revisé Historical Search y Configuration en teléfono y formato ancho",
   "evidence": "Ambas vistas previas correctas; 7 pantallas sin scrPlantilla; nombres sin sufijo; sin errores de fórmula; app Saved (Unpublished)"
  },
  {
   "start": "2026-09-30T12:52:00Z",
   "minutes": 20,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-07",
   "attempt": 1,
   "result": "AVANCE",
   "kind": "prod",
   "category": "DISENO",
   "summary": "Estandaricé el encabezado y título de Historical Search y Configuration; eliminé scrPlantilla y ajusté la galería de carpetas para móvil",
   "evidence": "7 pantallas en el árbol; sin errores de fórmula; vista móvil de Configuration aún corta el botón Incremental; app guardada sin publicar"
  },
  {
   "start": "2026-09-30T12:28:00Z",
   "minutes": 24,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-06",
   "attempt": 1,
   "result": "HECHA",
   "kind": "prod",
   "category": "DISENO",
   "summary": "Apliqué encabezado y título estándar en Projects, Tasks y Review; moví lblTasksCount para separarlo del subtítulo y corregí el bloque YAML literal del texto",
   "evidence": "Vista previa móvil de las 3 pantallas; sin errores de fórmula; app Saved (Unpublished)"
  },
  {
   "start": "2026-09-30T12:11:00Z",
   "minutes": 17,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-05",
   "attempt": 3,
   "result": "HECHA",
   "kind": "prod",
   "category": "DISENO",
   "summary": "Apliqué el estándar a My Day y Diagnostics y conservé Refresh",
   "evidence": "Vista previa móvil y tableta; Refresh terminó; navegación a las 7 pantallas comprobada; No formula errors; guardada sin publicar"
  },
  {
   "start": "2026-09-30T11:59:00Z",
   "minutes": 9,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-05",
   "attempt": 2,
   "result": "AVANCE",
   "kind": "prod",
   "category": "DISENO",
   "summary": "Preparé bloques estándar para encabezados y títulos de My Day y Diagnostics",
   "evidence": "Dos bloques YAML locales; aún falta aplicarlos y comprobar la vista previa en Studio"
  },
  {
   "start": "2026-09-30T11:55:00Z",
   "minutes": 4,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-05",
   "attempt": 1,
   "result": "AVANCE",
   "kind": "prod",
   "category": "DISENO",
   "summary": "Inspeccioné la estructura de My Day antes de sustituir el encabezado",
   "evidence": "Confirmé que RefreshDashboardButton actualiza las listas; conservarlo al aplicar el estándar"
  },
  {
   "start": "2026-09-30T11:42:00Z",
   "minutes": 13,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-04",
   "attempt": 1,
   "result": "HECHA",
   "kind": "prod",
   "category": "DISENO",
   "summary": "Creé scrPlantilla con header, título y tarjeta de muestra; amplié el menú para evitar cortes",
   "evidence": "Vista previa correcta en escritorio y iPhone 390x844; sin errores de fórmula; app guardada sin publicar. Power Apps asignó sufijo a un control que colisiona con otra pantalla"
  },
  {
   "start": "2026-09-30T11:40:00Z",
   "minutes": 2,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-03",
   "attempt": 1,
   "result": "HECHA",
   "kind": "prod",
   "category": "FORMULA_PA",
   "summary": "Tema y navegación pegados en App.Formulas",
   "evidence": "Studio mostró No formula errors present y el guardado terminó"
  },
  {
   "start": "2026-09-30T11:28:00Z",
   "minutes": 6,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-02",
   "attempt": 1,
   "result": "HECHA",
   "kind": "prod",
   "category": "DISENO",
   "summary": "Tema y versiones alineados con la referencia",
   "evidence": "Colores, tamaños y bordes actualizados; controles con versión documentados; diferencias entre botones separados de referencia y gallery de Nav registradas"
  },
  {
   "start": "2026-09-30T11:18:00Z",
   "minutes": 10,
   "account": "personal",
   "entrega": "E1",
   "task": "E1-01",
   "attempt": 1,
   "result": "HECHA",
   "kind": "prod",
   "category": "DISENO",
   "summary": "Bloques de referencia copiados y versiones anotadas",
   "evidence": "2 archivos guardados desde View code; 26 controles con versión identificados; anotaciones comprobadas"
  },
  {
   "start": "2026-09-30T10:56:00Z",
   "minutes": 1,
   "account": "personal",
   "entrega": "E0",
   "task": "E0-09",
   "attempt": 1,
   "result": "HECHA",
   "kind": "prod",
   "category": "OTRO",
   "summary": "Issue de aceptación procesado; E0 aceptada",
   "evidence": "Issue 1 confirmado por la cuenta autora; Oscar confirmó por chat la prueba en ambos equipos; decisión registrada y issue cerrado"
  },
  {
   "start": "2026-09-30T07:35:00Z",
   "minutes": 3,
   "account": "personal",
   "entrega": "T",
   "task": "T-01",
   "attempt": 7,
   "result": "HECHA",
   "kind": "prod",
   "category": "DOCUMENTACION",
   "summary": "Configuré los dos horarios del revisor y generé la revisión manual",
   "evidence": "Tareas Codex diarias a las 04:30 y 17:00 hora local Central; control/REVISION.md generado y comprometido por separado"
  },
  {
   "start": "2026-09-30T06:59:00Z",
   "minutes": 30,
   "account": "personal",
   "entrega": "T",
   "task": "T-01",
   "attempt": 6,
   "result": "HECHA",
   "kind": "prod",
   "category": "OTRO",
   "summary": "Tablero publicado y actualización horaria configurada",
   "evidence": "URL HTTP 200; Get-ScheduledTask PFA Tablero listo, última ejecución LastTaskResult 0, próxima ejecución dentro de 1 hora"
  },
  {
   "start": "2026-09-30T06:57:00Z",
   "minutes": 2,
   "account": "personal",
   "entrega": "T",
   "task": "T-01",
   "attempt": 5,
   "result": "HECHA",
   "kind": "prod",
   "category": "OTRO",
   "summary": "Repositorio público creado y Pages activado en main y raíz",
   "evidence": "Repositorio público visible; clon local en la ruta configurada; GitHub Pages compilado y devuelve HTTP 200 en https://oscarmarquez83.github.io/pfa-tablero/"
  },
  {
   "start": "2026-09-30T06:56:00Z",
   "minutes": 1,
   "account": "personal",
   "entrega": "T",
   "task": "T-01",
   "attempt": 4,
   "result": "HECHA",
   "kind": "prod",
   "category": "AUTH",
   "summary": "Autenticación de GitHub CLI guardada y Git configurado para usarla",
   "evidence": "gh auth status identifica una sesión activa en github.com; gh auth setup-git terminó correctamente"
  },
  {
   "start": "2026-09-30T06:50:00Z",
   "minutes": 0,
   "account": "personal",
   "entrega": "T",
   "task": "T-01",
   "attempt": 3,
   "result": "SIN_AVANCE",
   "kind": "unprod",
   "category": "AUTH",
   "summary": "La sesión de GitHub CLI no quedó guardada para la cuenta de Oscar",
   "evidence": "gh auth status informa que no hay sesión en hosts de GitHub; no se encontró configuración en las rutas estándar"
  },
  {
   "start": "2026-09-30T06:41:00Z",
   "minutes": 4,
   "account": "personal",
   "entrega": "T",
   "task": "T-01",
   "attempt": 2,
   "result": "AVANCE",
   "kind": "prod",
   "category": "OTRO",
   "summary": "GitHub CLI 2.102.0 descargado del release oficial, instalado en perfil de usuario y añadido al PATH; falta autenticación interactiva de Oscar",
   "evidence": "gh --version devuelve 2.102.0; Get-Command gh resuelve C:\\Users\\oscar\\AppData\\Local\\Programs\\gh\\bin\\gh.exe; hash SHA256 AE64E556ECC240B200F7EBA60D550E4BB60D78E860E69DD88C449405B86067F4"
  },
  {
   "start": "2026-09-30T06:40:00Z",
   "minutes": 0,
   "account": "personal",
   "entrega": "E0",
   "task": "E0-04",
   "attempt": 2,
   "result": "HECHA",
   "kind": "prod",
   "category": "OTRO",
   "summary": "Import-Csv validó las tres filas E0-01 a E0-03 y las 11 columnas",
   "evidence": "5 filas totales legibles; 3 tareas E0 verificadas con horas presentes"
  },
  {
   "start": "2026-09-30T06:25:00Z",
   "minutes": 1,
   "account": "personal",
   "entrega": "T",
   "task": "T-01",
   "attempt": 1,
   "result": "AVANCE",
   "kind": "prod",
   "category": "OTRO",
   "summary": "GitHub CLI y WinGet/App Installer no están instalados; se solicitan instalación y autenticación supervisadas",
   "evidence": "gh --version y winget no están disponibles; Get-AppxPackage confirmó que falta App Installer"
  },
  {
   "start": "2026-09-30T06:23:00Z",
   "minutes": 1,
   "account": "personal",
   "entrega": "E0",
   "task": "E0-04",
   "attempt": 1,
   "result": "AVANCE",
   "kind": "prod",
   "category": "OTRO",
   "summary": "CSV legible y con las tres tareas requeridas; Excel no pudo iniciarse desde esta sesión",
   "evidence": "Import-Csv correcto; apertura automatizada de Excel falló; requiere confirmación en la aplicación"
  },
  {
   "start": "2026-09-30T06:22:00Z",
   "minutes": 1,
   "account": "personal",
   "entrega": "E0",
   "task": "E0-03",
   "attempt": 1,
   "result": "HECHA",
   "kind": "prod",
   "category": "DOCUMENTACION",
   "summary": "Aviso de congelado agregado a los cuatro documentos",
   "evidence": "Los cuatro empiezan con el texto aprobado"
  },
  {
   "start": "2026-09-30T06:22:00Z",
   "minutes": 0,
   "account": "personal",
   "entrega": "E0",
   "task": "E0-02",
   "attempt": 1,
   "result": "HECHA",
   "kind": "prod",
   "category": "OTRO",
   "summary": "Verificación de los archivos requeridos para E0",
   "evidence": "AGENTS.md, control/, design/, dashboard/, build_dashboard.py y publish_dashboard.ps1 existen"
  },
  {
   "start": "2026-09-30T06:21:00Z",
   "minutes": 0,
   "account": "personal",
   "entrega": "E0",
   "task": "E0-01",
   "attempt": 1,
   "result": "HECHA",
   "kind": "prod",
   "category": "OTRO",
   "summary": "Commit local de línea base con el estado completo del repositorio",
   "evidence": "79f0f54; 207 archivos; árbol limpio tras el commit"
  }
 ],
 "ideas": [
  {
   "id": "HZ-01",
   "date": "2026-09-30",
   "text": "PFA_Messages exige 22 columnas obligatorias, 2 de ellas lookups; eso bloqueó la persistencia en el Bloque 2. Revisar cuáles vuelven a ser obligatorias cuando la carga sea automática",
   "found": "Revisión de Claude",
   "target": "E5",
   "status": "Asignado"
  },
  {
   "id": "HZ-02",
   "date": "2026-09-30",
   "text": "El flujo antiguo PFA_InventoryMailFolders no lee Outlook: solo cuenta filas de PFA_MailFolders",
   "found": "Revisión de Claude",
   "target": "E2",
   "status": "Incorporado en E2-02 (flujo nuevo)"
  },
  {
   "id": "HZ-03",
   "date": "2026-09-30",
   "text": "Los 14 flujos antiguos siguen en la solución. Decidir si se eliminan o se archivan",
   "found": "Revisión de Claude",
   "target": "E6",
   "status": "Asignado"
  },
  {
   "id": "HZ-04",
   "date": "2026-09-30",
   "text": "Correos que llegan al Inbox y todavía no se movieron a una carpeta de proyecto",
   "found": "Oscar",
   "target": "E7",
   "status": "Asignado"
  },
  {
   "id": "HZ-05",
   "date": "2026-09-30",
   "text": "Proyectos con varios proyectos dentro: posible vista de \"programa\" que agrupe los subproyectos",
   "found": "Oscar",
   "target": "E2",
   "status": "Incorporado en E2-05 y E2-06"
  },
  {
   "id": "HZ-06",
   "date": "2026-09-30",
   "text": "El contenido interno de las pantallas no sigue un estándar. Cada entrega rehace con el estándar la parte que usa",
   "found": "Oscar",
   "target": "E1 en adelante",
   "status": "Incorporado en la regla D-013"
  },
  {
   "id": "HZ-07",
   "date": "2026-09-30",
   "text": "Publicar en el tablero el diagrama de flujos del proyecto",
   "found": "Oscar",
   "target": "T",
   "status": "Asignado"
  },
  {
   "id": "HZ-08",
   "date": "2026-09-30",
   "text": "En Diagnostics, el texto de estados se superpone en la vista de teléfono; revisar al rediseñar Diagnostics",
   "found": "E1-08",
   "target": "E5",
   "status": "Asignado"
  },
  {
   "id": "HZ-09",
   "date": "2026-09-30",
   "text": "La galería de carpetas de Configuration se modificó durante E1; en la app publicada, las etiquetas de sus botones quedan recortadas verticalmente. Detener cambios ahí hasta E2",
   "found": "Incidente INC-01",
   "target": "E2",
   "status": "Asignado"
  },
  {
   "id": "HZ-10",
   "date": "2026-09-30",
   "text": "En teléfono e iPad vertical, reemplazar la navegación horizontal desplazable por un botón que abra una lista vertical seleccionable; mantener botones en formato horizontal",
   "found": "Oscar",
   "target": "E1-10",
   "status": "Incorporado en E1-10"
  }
 ]
};

